config.yaml
=> Update social media icons

layouts/partials/navbar.html
=> Align navbar classes with theme

layouts/posts/list.html
=> Hide tag cloud on mobile devices

content/posts/scipy/internships/smit/index.md
=> Add SciPy Internship experience

content/posts/scipy/internships/smit/index.md
=> Fix CI on SciPy article

.pre-commit-config.yaml
=> Update precommit linters

.github/workflows/lint.yml
=> Update GH actions

content/posts/matplotlib/draw-all-graphs-of-n-nodes/index.md
=> Update alt-text in a mpl post

config.yaml
=> Use custom youtube url

config.yaml
=> Add discord footer icon

.pre-commit-config.yaml, assets/css/custom.css, requirements/developer.txt
=> Update pre-commit hooks

content/posts/scientific-python/2022-czi-grant/index.md
=> Add post: announcing 2022 CZI grant to Scientific Python

config.yaml
=> Fix link to main page

assets/css/custom.css
This should make #98 render quite a bit better (and all other posts, for that matter).
=> Reduce the default font size, increase the paragraph spacing

content/posts/numpy/fellowship-program/index.md, content/posts/numpy/first-developer-in-residence/index.md
@rgommers @InessaPawson 
I've done some minor tightening up of the text (cleaned up some word repetition, modified Sayed's quote a bit to convey the right sentiment), so please scan the text one more time.
=> Add NumPy Developer in Residence post

.github/dependabot.yml, requirements/developer.txt
=> Use dependabot

content/posts/scientific-python/2023-developer-summit/index.md, content/posts/scientific-python/dev-summit-1-sparse/index.md
Please add/remove/change whatever you think is relevant for this post.
I added @stefanv's name as author, but only because we thought we might meet on Tuesday to go over this (and to try accents with this version of markdown).
Please remove it and/or add other names as you see fit.
This is largely written based on the hackmd document: [Developer Summit Report -- scipy.sparse](https://hackmd.io/1Q2832LDR_2Uv_-cV-wnYg) 
- [NA ] Images have been compressed using a tool like `pngquant`.
=> Add developer summit 1: sparse post

content/posts/scientific-python/dev-summit-1-sparse/index.md, content/posts/scientific-python/dev-summit-1/index.md
=> Fix spelling

.pre-commit-config.yaml, content/posts/matplotlib/GSoC_2021_Final/index.md, content/posts/matplotlib/GSoC_2021_PreQuarter/index.md, content/posts/matplotlib/animated-polar-plot/index.md, content/posts/matplotlib/emoji-mosaic-art/index.md, content/posts/matplotlib/matplotlib-cyberpunk-style/index.md, content/posts/matplotlib/pyplot-vs-object-oriented-interface/index.md, content/posts/networkx/aTSP/a-closer-look-at-held-karp/index.md, content/posts/networkx/aTSP/completing-the-asadpour-algorithm/index.md, content/posts/networkx/aTSP/entropy-distribution-setup/index.md, content/posts/networkx/aTSP/entropy-distribution/index.md, content/posts/networkx/aTSP/finalizing-held-karp/index.md, content/posts/networkx/aTSP/finding-all-minimum-arborescences/index.md, content/posts/networkx/aTSP/held-karp-relaxation/index.md, content/posts/networkx/aTSP/held-karp-separation-oracle/index.md, content/posts/networkx/aTSP/implementing-the-iterators/index.md, content/posts/networkx/aTSP/my-summer-of-code-2021/index.md, content/posts/networkx/aTSP/sampling-a-spanning-tree/index.md, content/posts/networkx/aTSP/understanding-the-ascent-method/index.md, content/posts/networkx/vf2pp/node-ordering-Ti-updating/index.md, content/posts/scientific-python/alt-text-workshop-summary/index.md, content/posts/scientific-python/dev-summit-1/index.md, content/posts/scientific-python/scientific-python-project/index.md, content/posts/scipy/qmc-basics/index.md, layouts/posts/list.html
closes https://github.com/scientific-python/blog.scientific-python.org/issues/118
=> Add codespell to github actions and fix typos

config.yaml
Updating to sync with changes to main page in https://github.com/scientific-python/scientific-python.org/pull/429.
=> Sync with mainpage

content/about/_index.md
=> Sync with main page

content/posts/scipy/internships/smit/index.md
=> Fix for blacken-doc update

.dir-locals.el
Ensures indentation consistent with project expectations.
=> Meta: Add .dir-locals.el

assets/css/custom.css, layouts/_default/term.html, layouts/partials/head.html, layouts/partials/post_meta.html, layouts/partials/posts.html, layouts/partials/section.html, layouts/posts/list.html
See <https://github.com/scientific-python/blog.scientific-python.org/issues/130>.
=> Change: Condense and simplify all-posts page

assets/css/custom.css, layouts/_default/term.html, layouts/partials/head.html, layouts/partials/post_meta.html, layouts/partials/posts.html, layouts/partials/section.html, layouts/posts/list.html
#137 was merged, but the theme submodule was pointing to a commit that wasn't on the main branch of the theme. I did the following:
```
git pull origin main 
git reset --hard dbcbb8aca6b241f359e153ecd93a8b024dd409f7
git push -f origin main
git checkout -b fixtheme
git cherry-pick 0c541ab829f2418dd016c0f79f5f4cd75ba2a335
cd themes/scientific-python-hugo-theme/
git checkout main 
git pull origin main
cd ../..
git add themes/scientific-python-hugo-theme/
git commit 
git push jarrod fixtheme
```
=> Change: Condense and simplify all-posts page 

netlify.toml
=> Use dart sass

assets/css/custom.css, netlify.toml
=> Update theme (v0.3)

netlify.toml
=> Update theme (v0.5)

netlify.toml
=> Update theme (0.7)

netlify.toml
=> Update theme (v0.9)

assets/css/posts-comments.css, config.yaml, layouts/partials/posts/comments.html
Closes #113
Alternative to #154
=> Discourse comments

content/posts/matplotlib/visualising-usage-using-batteries/index.md
=> Update theme (v0.10)

config.yaml
=> Focus social media

.gitmodules
See https://github.com/scientific-python/scientific-python-hugo-theme/pull/489
=> Use atom-feed submodule from theme

Makefile, config.yaml
=> Fix for hugo-atom-feed submodule

config.yaml
=> Fix atom-feed

content/posts/networkx/outreachy2023/contribution-phase/index.md, content/posts/networkx/outreachy2023/internship/index.md, content/posts/networkx/vf2pp/ISO-feasibility-candidates/index.md, content/posts/networkx/vf2pp/graph-iso-vf2pp/index.md, content/posts/networkx/vf2pp/node-ordering-Ti-updating/index.md
=> Fix relrefs for upcoming release

config.yaml
=> Simplify tab text

netlify.toml
=> Update theme (v0.12)

netlify.toml
=> Update theme (v0.13)

content/_index.md
=> Use new grid syntax

content/posts/scientific-python/cookie/dev-summit-1-development-guide/index.md
=> Update theme (v0.14)

content/_index.md, content/about/_index.md
=> Replace grid1 shortcode with grid

netlify.toml
=> Update theme (v0.16)

content/posts/scipy/internships/_index.md
See <https://github.com/scientific-python/blog.scientific-python.org/issues/158>.
=> Add missing title (#158)

netlify.toml
=> Update theme (v0.17)

config.yaml
=> Link to tools

content/posts/numpy/numpy2/index.md
This is a draft trying to incorporate some of the things discussed last Wednesday.  I had thought @rgommers would do a major revision.  So this is a somewhat fresh start, which includes some of the things we discussed, but no idea if it at all what everyone had in mind.
It doesn't include some of the more detailed notes added to the old draft, I had the intention to reduce details of changes rather, but of course maybe some of the "cool new things" get's lost that way... 
*I am not attached to this at all*. There was hope a to release something on Sunday night shortly after the release to pypi.  I don't know if that is viable now, since I expected to do a much smaller iteration today and be finished earlier.
Pinging some more active/involved ones with no particular order/logic: @stefanv, …
=> Blog post about the NumPy 2 release

content/posts/numpy/numpy2/index.md
Just a minor edit in the wording of the blog post. Fantastic effort, everyone!
=> Minor edit

.pre-commit-config.yaml, content/posts/matplotlib/ipcc-sr15/index.md
=> Update pre-commit repos

netlify.toml
=> Update theme (v0.18)

netlify.toml
=> Update theme (v0.19)

content/posts/scientific-python/translations/index.md
Thanks @trallard for the heads up 😄 
- [N/A] The main subject relates to at least one project affiliated to the Scientific Python Ecosystem.
- [N/A] Images have been compressed using a tool like `pngquant`.
=> Fix link to pandas website in translations announcement post

netlify.toml
=> Update theme (v0.20)

netlify.toml
=> Use Python 3.13 on netlify

config.yaml
Setting was in the wrong place :roll_eyes:
=> Fix analytics configuration

netlify.toml
=> Update theme (v0.21)
